# These settings are synced to GitHub by https://probot.github.io/apps/settings/

 # See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: arcus.probot.test
  description: Test project to check the posibilities of Probot. 
  homepage: https://arcus..github.io/
  topics: github, probot
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: master
  allow_squash_merge: true

labels:
  - name: automation
    color: 00e5a8
    description: All issues related to project automation.

  - name: breaking-change
    color: e99695
    description: All issues that require to do a breaking change.
    
  - name: bug
    color: d73a4a
    description: Something isn't working
    
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file

milestones:
  - title: Project Setup
    description: All tasks related to creating a new Arcus project
    state: open

branches:
  - name: master
